= Simple MicroProfile Metric Tags Example

Simple Quarkus MicroProfile application that creates a metric with two tags. The domain model uses a "student", with a student either being part-time or full-time. There are two MicroProfile Metrics `@Counted` metrics that count the number of times the `/parttime` and `/fulltime` endpoints are called.

Instructions are included for viewing the metric on a Grafana dashboard.

== Compiling, testing, and packaging the application

Steps to see running demonstrates Metrics tags

. Build the application
+
--
[source,bash]
----
$ mvn clean package
----
--
+

. Run the application
+
--
.Terminal 1
[source,bash]
----
$ java -jar target/metrics-tags-1.0-SNAPSHOT-runner.jar
----

.Terminal 1 Sample Output
....
2020-01-06 18:10:52,240 INFO  [io.quarkus] (main) metrics-tags 1.0-SNAPSHOT (running on Quarkus 1.1.0.Final) started in 0.743s. Listening on: http://0.0.0.0:8080
2020-01-06 18:10:52,255 INFO  [io.quarkus] (main) Profile prod activated.
2020-01-06 18:10:52,255 INFO  [io.quarkus] (main) Installed features: [cdi, resteasy, smallrye-metrics]
....
--

. Send requests to the endpoints a few times
+
--
.Terminal 2
[source,bash]
----
# Part time endpoint
$ curl -s localhost:8080/student/parttime
$ curl -s localhost:8080/student/parttime
# Full time endpoint
$ curl -s localhost:8080/student/fulltime
$ curl -s localhost:8080/student/fulltime
$ curl -s localhost:8080/student/fulltime
----
--
. View the metrics endpoint
+
--
.Terminal 2
[source,bash]
----
$ curl -s localhost:8080/metrics/application | grep status
----

.Terminal 2 Sample Output
....
# TYPE application_status_total counter
application_status_total{status="part-time"} 1.0
application_status_total{status="full-time"} 3.0
....
--

. Stop the application
+
--
.Terminal 1
[source,bash]
----
# Press CTRL-C
----
--

== View dashboard in Grafana

. Build the docker container
+
--
.Terminal 1
[source,bash]
----
$ docker build \
    -t acme/metrics-tags:1.0 \
    -f src/main/docker/Dockerfile.jvm \
    .
----
--

. Start Prometheus, Grafana, and application to see the counter metric with tags (part-time and full-time)
+
--
.Terminal 1
[source,bash]
----
$ cd docker
$ docker-compose up
----
--
+

. Get Prometheus IP Address
+
--
.Terminal 2
[source,bash]
----
docker inspect docker_prom_1 | grep IPA
----
.Terminal 2 Sample Output
....
...
...
"SecondaryIPAddresses": null,
"IPAddress": "",
    "IPAMConfig": null,
    "IPAddress": "172.27.0.3", <1>
...
...
....
<1> The IP address
--

. Login in to grafana
.. Open http://localhost:3000/datasources in a browser
.. Username `admin`, password `admin`

. Add a datasource
.. Click `Add data source`
.. Choose Prometheus
.. Use ip address from step 4 to fill in url field (Ex: http://localhost:172.27.0.3:9090).
.. Press Save & Test
.. Go back to main screen

. Add Grafana Dashboard
.. In the upper-left hand corner, hover the mouse cursor over the large `+` sign, then select `Import`. This brings up the Import screen.
.. Click `Upload .json File`, navigate to the project directory's `docker` subdirectory, and select `Student Status Dashboard.json`
.. Click `Import`

. Generate requests to graph the results
.. Run `curl -i localhost:8080/student/fulltime` a bunch of times. The dashboard shows the most recent 5 minutes of data with a 5 second refresh. Watch the `Student Status Requests` dashboard update as the endpoint consumes requests.
.. Run `curl -i localhost:8080/student/parttime` a bunch of times. The part time status updates.

The graph only contains one attribute, even though two graph lines are shown (one for each status).

. View the graph configuration
.. Click on the `Student status Requests` title and select `Edit`
.. Note that the only attribute name is `application_status_total`, but a graph line is shown for each Metric tag.
.. The legend Format contains `{{student}}`, which is a template parameter to display the status text (`part-time` or `full time`). The `student` tag name is defined by the @Counted(name="status") parameter.

NOTE: With MicroProfile Metrics, tags can be applied globally by defining a `MP_METRICS_TAGS` environment variable or by defining tags using the `mp.metrics.tags` environment variable directory. Tag format is limited to the `[a-zA-Z_][a-zA-Z0-9_]*`` regular expression. Uncomment the `mp.metrics.tags` property in `application.properties` to see this in action.