{
 "title": "Frontend Dashboard",
 "time": { "from": "now/d", "to": "now" },
 "panels": [
  {
   "title": "getStudents Mean",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "application_getStudentsTime_mean_seconds",
     "legendFormat": "Mean duration of getStudents call"
    }
   ]
  },
  {
   "title": "getStudents Fallback",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 5, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "application_ft_org_acme_FrontendResource_getStudents_fallback_calls_total",
     "legendFormat": "Number of getStudents Fallback Calls"
    }
   ]
  },
  {
   "title": "getStudents Mean",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "application_getStudentsTime_mean_seconds"
    }
   ]
  },
  {
   "title": "Frontend /list Calls",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "application_getStudentsTime_seconds_count"
    }
   ]
  },
  {
   "title": "List Students Circuit Breaker",
   "type": "graph",
   "description": "Graphs time spent in each circuit breaker states",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "application_ft_org_acme_FrontendResource_getStudents_circuitbreaker_closed_total/10000000000",
     "legendFormat": "Closed"
    },
    {
     "expr": "application_ft_org_acme_FrontendResource_getStudents_circuitbreaker_halfOpen_total/10000000000",
     "legendFormat": "Half-Open"
    },
    {
     "expr": "application_ft_org_acme_FrontendResource_getStudents_circuitbreaker_open_total/1000000000",
     "legendFormat": "Open"
    }
   ]
  }
 ]
}